package com.gigaspaces.internal.server.space.repartitioning;

public class AutoGeneratedIdNotSupportedException extends RuntimeException {
    public AutoGeneratedIdNotSupportedException(String message) {
        super(message);
    }
}
