package com.gigaspaces.internal.server.space.repartitioning;

public class AutoGeneratedIdNotSupportedException extends RuntimeException {
    private static final long serialVersionUID = -2030423532582940096L;
    public AutoGeneratedIdNotSupportedException(String message) {
        super(message);
    }
}
