package com.gigaspaces.demo;

/**
 * This class was auto-generated by GigaSpaces
 */
public class Person {
    private int id;
    private String name;

    public Person() {
    }

    public int getid() {
        return id;
    }
    public void setid(int id) {
        this.id = id;
    }

    public String getname() {
        return name;
    }
    public void setname(String name) {
        this.name = name;
    }
}
