package com.gigaspaces.demo;

/**
 * This class was auto-generated by GigaSpaces
 */
public class Person {
    private int id;
    private String name;
    private long auto-generate;

    public Person() {
    }

    public int getid() {
        return id;
    }
    public void setid(int id) {
        this.id = id;
    }

    public String getname() {
        return name;
    }
    public void setname(String name) {
        this.name = name;
    }

    @SpaceId(autoGenerate=true)
    public long getauto-generate() {
        return auto-generate;
    }
    public void setauto-generate(long auto-generate) {
        this.auto-generate = auto-generate;
    }

}
