package com.gigaspaces.demo;

import com.gigaspaces.annotation.pojo.*;
import com.gigaspaces.internal.utils.CompoundIdUtils;
import com.gigaspaces.metadata.index.SpaceIndexType;
import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * This class was auto-generated by GigaSpaces
 */
@Entity(name = "SimpleCompoundIdPojo")
@Table(name = "SimpleCompoundIdPojo")
@SpaceClass
public class SimpleCompoundIdPojo {
    private SimpleCompoundIdKeyInner compoundIdKey;
    private Integer field1;
    private Integer field2;

    public SimpleCompoundIdPojo() {
    }


    @SpaceId(autoGenerate = false)
    @EmbeddedId
    public SimpleCompoundIdKeyInner getCompoundIdKey() {
        return compoundIdKey;
    }
    public void setCompoundIdKey(SimpleCompoundIdKeyInner compoundIdKey) {
        this.compoundIdKey = compoundIdKey;
    }

    @Column(name = "FIELD1")
    public Integer getField1() {
        return field1;
    }
    public void setField1(Integer field1) {
        this.field1 = field1;
    }

    @Column(name = "FIELD2")
    public Integer getField2() {
        return field2;
    }
    public void setField2(Integer field2) {
        this.field2 = field2;
    }

    @Embeddable
    public static class SimpleCompoundIdKeyInner  implements Serializable {

        private String fieldKey1;
        private String fieldKey2;

        public SimpleCompoundIdKeyInner() {
        }

        @Column(name = "FIELDKEY1")
        public String getFieldKey1() {
            return fieldKey1;
        }
        public void setFieldKey1(String fieldKey1) {
            this.fieldKey1 = fieldKey1;
        }

        @Column(name = "FIELDKEY2")
        public String getFieldKey2() {
            return fieldKey2;
        }
        public void setFieldKey2(String fieldKey2) {
            this.fieldKey2 = fieldKey2;
        }

        public String toString()
        {
            return CompoundIdUtils.getCompoundIdToString(fieldKey1,fieldKey2);
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            SimpleCompoundIdKeyInner that = (SimpleCompoundIdKeyInner) o;
            return CompoundIdUtils.getCompoundIdEquals(new Object[]{that.getFieldKey1(),that.getFieldKey2()},new Object[]{fieldKey1, fieldKey2});
        }

        @Override
        public int hashCode() {
            return CompoundIdUtils.getCompoundIdHashCode(fieldKey1, fieldKey2);
        }
    }
}
