package com.gigaspaces.demo;

import com.gigaspaces.entry.CompoundSpaceId;
import com.gigaspaces.annotation.pojo.*;
import javax.persistence.*;

/**
 * This class was auto-generated by GigaSpaces
 */
@Entity(name = "SimpleCompoundIdPojo")
@Table(name = "SimpleCompoundIdPojo")
@SpaceClass
public class SimpleCompoundIdPojo {
    private Key key;
    private Integer field1;
    private Integer field2;

    public SimpleCompoundIdPojo() {
    }

    @SpaceId
    @EmbeddedId
    public Key getKey() {
        return key;
    }
    public void setKey(Key key) {
        this.key = key;
    }

    @Column(name = "FIELD1")
    public Integer getField1() {
        return field1;
    }
    public void setField1(Integer field1) {
        this.field1 = field1;
    }

    @Column(name = "FIELD2")
    public Integer getField2() {
        return field2;
    }
    public void setField2(Integer field2) {
        this.field2 = field2;
    }

    @Embeddable
    public static class Key extends CompoundSpaceId {

        public Key() {
            super(2);
        }

        public Key(String fieldKey1, String fieldKey2) {
            super(fieldKey1,fieldKey2);
        }

        @Column(name = "FIELDKEY1")
        public String getFieldKey1() {
            return (String) getValue(0);
        }
        public void setFieldKey1(String fieldKey1) {
            setValue(0,fieldKey1);
        }

        @Column(name = "FIELDKEY2")
        public String getFieldKey2() {
            return (String) getValue(1);
        }
        public void setFieldKey2(String fieldKey2) {
            setValue(1,fieldKey2);
        }
    }
}
